# Generated by Django 3.2.3 on 2021-10-29 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdBanner',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('deeplink_destination', models.TextField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'AdBanner',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('phone_number', models.TextField()),
            ],
            options={
                'db_table': 'Buyer',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='BuyerAddress',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.TextField()),
                ('contact_phone_number', models.TextField()),
                ('create_date', models.DateTimeField()),
                ('buyer', models.ForeignKey(db_column='buyerId', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='api.buyer')),
            ],
            options={
                'db_table': 'BuyerAddress',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('vehicle_info', models.TextField()),
                ('vehicle_plate_number', models.TextField()),
                ('contact_phone_number', models.TextField()),
                ('rating_score_avg', models.FloatField()),
                ('create_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'Driver',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('location_lat', models.FloatField()),
                ('location_lng', models.FloatField()),
                ('rating_score_avg', models.FloatField()),
            ],
            options={
                'db_table': 'Merchant',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MerchantCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('thumbUrl', models.TextField()),
            ],
            options={
                'db_table': 'MerchantCategory',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.TextField(blank=True, null=True)),
                ('delivery_address_text', models.TextField(blank=True, db_column='delivery_address', null=True)),
                ('delivery_phone_number', models.TextField(blank=True, null=True)),
                ('total_amount', models.FloatField()),
                ('status', models.IntegerField()),
                ('order_date', models.DateTimeField()),
                ('last_update_date', models.DateTimeField()),
                ('buyer', models.ForeignKey(db_column='buyerId', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='api.buyer')),
                ('delivery_address', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='api.buyeraddress')),
                ('driver', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.driver')),
                ('merchantid', models.ForeignKey(db_column='merchantId', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='api.merchant')),
            ],
            options={
                'db_table': 'Order',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
                ('type', models.IntegerField(blank=True, null=True)),
                ('value', models.FloatField()),
                ('isApplyAllMerchant', models.BooleanField(db_column='isApplyAllMerchant')),
                ('isApplyAllBuyer', models.BooleanField(db_column='isApplyAllBuyer')),
            ],
            options={
                'db_table': 'Voucher',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='BuyerLoginInfo',
            fields=[
                ('buyer', models.OneToOneField(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='api.buyer')),
                ('user_name', models.TextField(unique=True)),
                ('user_3rd_id', models.TextField(blank=True, null=True)),
                ('token', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'BuyerLoginInfo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProductGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
                ('merchant', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='api.merchant')),
            ],
            options={
                'db_table': 'ProductGroup',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sku', models.TextField(unique=True)),
                ('name', models.TextField()),
                ('price', models.FloatField()),
                ('unit_name', models.TextField(blank=True)),
                ('group', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='api.productgroup')),
                ('merchant', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='api.merchant')),
            ],
            options={
                'db_table': 'Product',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('create_date', models.DateTimeField()),
                ('order', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='api.order')),
                ('product', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='api.product')),
            ],
            options={
                'db_table': 'OrderProduct',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='order',
            name='voucher',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.voucher'),
        ),
        migrations.CreateModel(
            name='MerchantVoucher',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('merchant', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='api.merchant')),
                ('voucher', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='api.voucher')),
            ],
            options={
                'db_table': 'MerchantVoucher',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MerchantBuyerFavorite',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('status', models.BooleanField()),
                ('buyer', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='api.buyer')),
                ('merchant', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='api.merchant')),
            ],
            options={
                'db_table': 'MerchantBuyerFavorite',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='merchant',
            name='category',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='api.merchantcategory'),
        ),
        migrations.CreateModel(
            name='DriverOrderRating',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('driver_rating_score', models.FloatField()),
                ('order_rating_score', models.FloatField()),
                ('create_date', models.DateTimeField()),
                ('driver', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='api.driver')),
                ('order', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='api.order')),
            ],
            options={
                'db_table': 'DriverOrderRating',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='BuyerVoucher',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('buyer', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='api.buyer')),
                ('voucher', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='api.voucher')),
            ],
            options={
                'db_table': 'BuyerVoucher',
                'managed': True,
            },
        ),
    ]
