# Generated by Django 3.2.9 on 2021-11-20 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdBanner',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subject', models.TextField()),
                ('description', models.TextField()),
                ('deeplink_destination', models.TextField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('thumbUrl', models.ImageField(upload_to='banner')),
            ],
        ),
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('phone_number', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='BuyerAddress',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.TextField()),
                ('contact_phone_number', models.TextField()),
                ('create_date', models.DateTimeField()),
                ('buyer', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='api.buyer')),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('vehicle_info', models.TextField()),
                ('vehicle_plate_number', models.TextField()),
                ('contact_phone_number', models.TextField()),
                ('rating_score_avg', models.FloatField()),
                ('create_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('address', models.TextField(blank=True, null=True)),
                ('location_lat', models.FloatField()),
                ('location_lng', models.FloatField()),
                ('thumbUrl', models.ImageField(blank=True, default='', upload_to='merchant')),
                ('rating_score_avg', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='MerchantCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('thumbUrl', models.ImageField(blank=True, upload_to='category')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.TextField()),
                ('delivery_address_text', models.TextField(blank=True, null=True)),
                ('delivery_phone_number', models.TextField(blank=True, null=True)),
                ('total_amount', models.FloatField()),
                ('order_status', models.CharField(choices=[('ac', 'Accepted'), ('pk', 'Packing'), ('dv', 'Delivering'), ('ss', 'Success'), ('fl', 'Fail'), ('cn', 'Cancel')], max_length=2)),
                ('voucher_code', models.TextField(blank=True, null=True)),
                ('total_before_discount', models.FloatField()),
                ('voucher_discount', models.FloatField()),
                ('shop_name', models.TextField()),
                ('shop_address', models.TextField()),
                ('item_count', models.IntegerField(default=0)),
                ('order_date', models.DateTimeField()),
                ('last_update_date', models.DateTimeField()),
                ('buyer', models.ForeignKey(db_column='buyerId', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='api.buyer')),
                ('delivery_address', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='api.buyeraddress')),
                ('driver', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.driver')),
                ('merchant', models.ForeignKey(db_column='merchantId', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='api.merchant')),
            ],
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('voucher_type', models.CharField(choices=[('pc', 'Discount percent'), ('dc', 'Discount amount')], default='pc', max_length=2)),
                ('value', models.FloatField()),
                ('isApplyAllMerchant', models.BooleanField()),
                ('isApplyAllBuyer', models.BooleanField()),
                ('start_date', models.DateTimeField()),
                ('last_date', models.DateTimeField()),
                ('min_order_total', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='BuyerLoginInfo',
            fields=[
                ('buyer', models.OneToOneField(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='api.buyer')),
                ('user_name', models.TextField(unique=True)),
                ('user_3rd_id', models.TextField(blank=True, null=True)),
                ('token', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
                ('merchant', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='api.merchant')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sku', models.TextField(unique=True)),
                ('name', models.TextField()),
                ('price', models.FloatField()),
                ('unit_name', models.TextField(blank=True)),
                ('thumbUrl', models.ImageField(blank=True, default='', upload_to='product')),
                ('group', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='api.productgroup')),
            ],
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('total', models.FloatField()),
                ('product_name', models.TextField(blank=True, default='')),
                ('create_date', models.DateTimeField()),
                ('order', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='api.order')),
                ('product', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='api.product')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='voucher',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.voucher'),
        ),
        migrations.CreateModel(
            name='MerchantVoucher',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('merchant', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='api.merchant')),
                ('voucher', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='api.voucher')),
            ],
        ),
        migrations.CreateModel(
            name='MerchantBuyerFavorite',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('status', models.BooleanField()),
                ('buyer', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='api.buyer')),
                ('merchant', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='api.merchant')),
            ],
        ),
        migrations.AddField(
            model_name='merchant',
            name='category',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='api.merchantcategory'),
        ),
        migrations.CreateModel(
            name='FirebaseBuyer',
            fields=[
                ('uid', models.TextField(primary_key=True, serialize=False)),
                ('buyer', models.OneToOneField(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='api.buyer')),
            ],
        ),
        migrations.CreateModel(
            name='DriverOrderRating',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('driver_rating_score', models.FloatField()),
                ('order_rating_score', models.FloatField()),
                ('create_date', models.DateTimeField()),
                ('driver', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='api.driver')),
                ('order', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='api.order')),
            ],
        ),
        migrations.CreateModel(
            name='BuyerVoucher',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('buyer', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='api.buyer')),
                ('voucher', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='api.voucher')),
            ],
        ),
    ]
