# Generated by Django 3.2.9 on 2021-11-23 03:03

from django.db import migrations
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchant',
            name='location_lat',
        ),
        migrations.RemoveField(
            model_name='merchant',
            name='location_lng',
        ),
        migrations.AddField(
            model_name='buyeraddress',
            name='location',
            field=location_field.models.plain.PlainLocationField(default=None, max_length=63, null=True),
        ),
        migrations.AddField(
            model_name='merchant',
            name='location',
            field=location_field.models.plain.PlainLocationField(default=None, max_length=63, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_location',
            field=location_field.models.plain.PlainLocationField(default=None, max_length=63, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shop_location',
            field=location_field.models.plain.PlainLocationField(default=None, max_length=63, null=True),
        ),
    ]
