# Generated by Django 3.2.9 on 2022-01-08 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211123_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='email',
            field=models.TextField(blank=True, default=''),
        ),
    ]
