# Generated by Django 3.2.9 on 2022-01-09 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_buyer_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIConfig',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('value', models.TextField()),
                ('status', models.BooleanField()),
            ],
        ),
    ]
